# config/packages/security.yaml
security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        # Spécifiez le hasher bcrypt pour l'entité User avec un coût de 12
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        # Utilisation d'un fournisseur d'utilisateurs basé sur l'entité User
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # Le provider en mémoire
        users_in_memory:
            memory: null

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            # Autres configurations de sécurité pour votre application principale

        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - App\Security\JwtAuthenticator

    access_control:
        # Accès pour les utilisateurs pleinement authentifiés pour l'API
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }




when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10









when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

